// <auto-generated />
using System;
using Gym_api.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_api.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20250122184906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_api.Model.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1133,
                            Hour = "Monday 15:30",
                            Name = "Yoga",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 1088,
                            Hour = "Thuesday 16:30",
                            Name = "Pilates",
                            Rating = 2.7000000000000002
                        },
                        new
                        {
                            Id = 1153,
                            Hour = "Friday 18:30",
                            Name = "Crossfit",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 1232,
                            Hour = "Saturday 10:00",
                            Name = "Stretching",
                            Rating = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("Gym_api.Model.GymMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("GymMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentId = 1133,
                            JoinDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Standard",
                            Name = "John",
                            Surname = "Deer"
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentId = 1088,
                            JoinDate = new DateTime(2024, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Standard",
                            Name = "Kamil",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentId = 1133,
                            JoinDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Premium",
                            Name = "Piotr",
                            Surname = "Stanowski"
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentId = 1153,
                            JoinDate = new DateTime(2024, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Premium",
                            Name = "Jakub",
                            Surname = "Stanley"
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentId = 1232,
                            JoinDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Premium",
                            Name = "Elon",
                            Surname = "Musk"
                        },
                        new
                        {
                            Id = 6,
                            EnrollmentId = 1153,
                            JoinDate = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Standard",
                            Name = "Kornelia",
                            Surname = "Casowsky"
                        },
                        new
                        {
                            Id = 7,
                            EnrollmentId = 1153,
                            JoinDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipType = "Plus",
                            Name = "Martin",
                            Surname = "Stankiewicz"
                        });
                });

            modelBuilder.Entity("Gym_api.Model.GymMember", b =>
                {
                    b.HasOne("Gym_api.Model.Enrollment", null)
                        .WithMany("GymMembers")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gym_api.Model.Enrollment", b =>
                {
                    b.Navigation("GymMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
